### ISSUE TITLE
Additional endorsement data to enter

### ISSUE THREAD

**Issue by kkashin** [johnmyleswhite/sf_politics#11]
- [x] SEIU 1021: http://www.seiu1021.org/seiu-1021-endorsements-2016/
- [x] SF Fire Fighters Local 798: http://myemail.constantcontact.com/San-Francisco-Firefighters-Local-798-Voting-Guide.html?soid=1114865855684&aid=q8nKHX0jyLo
- [x] Bernal Heights Democratic Club https://www.facebook.com/bernalheightsdemocraticclub/posts/438719943003790 
- [x] SF Bay Guardian: http://www.sfbg.com/2016/05/10/endorsements-kim-for-state-senate-sanders-for-president-yes-on-c/
- [x] Sierra Club: http://sierraclub.org/san-francisco-bay/june2016endorsements#sf
- [x] AFT Local 2121: http://www.aft2121.org/get-political/2016-election-endorsements/
- [x] SF Labor Council: http://sflaborcouncil.org/politics/endorsements/ 
- [x] District 8 Democratic Club: https://www.facebook.com/D8Democrats/photos/a.156809127793555.36317.156808847793583/741150529359409/?type=3&theater / https://www.facebook.com/D8Democrats/posts/723410354466760
- [x] IFPTE Local 21: http://www.ifpte21.org/content/local-21-endorsements-june-7-primary-election
- [x] Affordable Housing Alliance: http://sfaffordablehousingalliance.org/
- [x] Evolve CA: http://www.evolve-ca.org/2016-endorsements/
- [x] NUHW: http://nuhw.org/endorsements/ (props)
- [x] Mark Farrell : http://www.marinatimes.com/2016/04/my-ballot-priorities-for-the-june-7-primary-election/
- [x] FDR Dems: http://us3.campaign-archive2.com/?u=82168ffd94fdebc83d0a2cacf&id=fbfae6a53d
- [x] Latina/o Young Democrats of San Francisco (candidates https://www.facebook.com/LYDSanFrancisco/posts/1556715027991927 and ballots https://www.facebook.com/LYDSanFrancisco/posts/1556718334658263)
- [x] San Francisco 4 Democracy: http://www.sf4democracy.org/?v=showsingle&id=289

**Comment by johnmyleswhite** [comment]
I just uploaded Bernal Heights Democratic Club

**Comment by johnmyleswhite** [comment]
The Evolve CA endorsements are really unique.

**Comment by johnmyleswhite** [comment]
Closed by c37e6c458a8bb26e7a03731a6bcaeae2913762b2
